# Generated by Django 4.2.7 on 2023-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_content_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=30),
        ),
    ]
