# Generated by Django 5.0.6 on 2024-06-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_messageimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to='voices/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='api.message')),
            ],
        ),
    ]
